#-------------------------------------------------------------------
# Site Settings
#-------------------------------------------------------------------

# Title of your website
title: "Aspectran"

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "The Next Generation Java Application Framework"

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "Aspectran is a lightweight, high‑performance framework for building both simple shell applications and large enterprise web services on the JVM. "

# Main author of the website
# See > authors.yml
author: juho_jeong

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'https://aspectran.com'
official_url: 'https://aspectran.com'
baseurl: '' # does not include hostname

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: 'https://github.com/aspectran/aspectran.github.io/edit/master'

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: '/images/'

# Logo Image
logo_img: "aspectran-logo.png"

# Logo size is 425x170 pixels
slogan_img: "aspectran-slogan.png"

# Footer Logo size is 100x100 pixels
logo_footer: "aspectran-site-logo.png"



#-------------------------------------------------------------------
# Build settings
#-------------------------------------------------------------------

# The language setting is used in /_includes/_head.html for html-settings
languages:
  'en': 'English'
  'ko': '한국어'
lang_order: ['en', 'ko']
default_lang: 'en'

# Handling Reading
safe: false
encoding: "utf-8"
keep_files: [".git"]
include: [".htaccess"]

# Exclude these files from your production _site
exclude:
#  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - INSTALL.md
  - CNAME
  - vendor
  - renovate.json
  - aspectran.github.io.iml


# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
highlighter: rouge
markdown_ext: "md"

kramdown:
  input: GFM


# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  profile: false
  ignore:
    envs: [development]


# Paginates all X entries
paginate: 10

# Pagination path › Important for blog page in /blog/ to work
paginate_path: "/blog/page:num/"
permalink: "/blog/:name/"

excerpt_separator: "<!--more-->"


#-------------------------------------------------------------------
# Default Settings
#-------------------------------------------------------------------

collections:
  pages:
    output: true
    permalink: "/:path/"
  examples:
    output: true
    permalink: "/examples/:path/"

defaults:
  - scope:
      path: "_pages/en" 				# an empty string here means all files in the project
    values:
      lang: "en"
      layout: "page"
      breadcrumb: true
      show_meta: false  	# Hide metadata for all pages
      author: "juho_jeong"  # Default author for pages
  - scope:
      path: "_pages/ko" 				# an empty string here means all files in the project
    values:
      lang: "ko"
      layout: "page"
      breadcrumb: true
      show_meta: false  	# Hide metadata for all pages
      author: "juho_jeong"  # Default author for pages
  - scope:
      path: "_posts/en"
    values:
      lang: "en"
      layout: "page"
      format: "plate margin article"
      breadcrumb: true
      permalink: "/en/blog/:name"
      excerpt_separator: <!--more-->
      show_meta: true       # Show metadata for all posts
      author: "juho_jeong"  # Default author for posts
  - scope:
      path: "_posts/ko"
    values:
      lang: "ko"
      layout: "page"
      format: "plate margin article"
      breadcrumb: true
      permalink: "/ko/blog/:name"
      excerpt_separator: <!--more-->
      show_meta: true       # Show metadata for all posts
      author: "juho_jeong"  # Default author for posts
  - scope:
      path: "_examples/en" 	# an empty string here means all files in the project
    values:
      lang: "en"
      layout: "page"
      breadcrumb: true
      permalink: "/en/examples/:name"
      show_meta: false  	# Hide metadata for all pages
      author: "juho_jeong"  # Default author for pages
  - scope:
      path: "_examples/ko" 	# an empty string here means all files in the project
    values:
      lang: "ko"
      layout: "page"
      permalink: "/ko/examples/:name"
      breadcrumb: true
      show_meta: false  	# Hide metadata for all pages
      author: "juho_jeong"  # Default author for pages



#-------------------------------------------------------------------
# SEO
# Verify Website to Webmaster Tools
#-------------------------------------------------------------------

#google_author:             "https://plus.google.com/u/0/118311555303973066167"
#google_site_verification:  "Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ"
#bing_webmastertools_id:    "0FB4C028ABCF07C908C54386ABD2D97F"
# alexa_verify_id:         ""



#-------------------------------------------------------------------
# Facebook
# Facebook-Optimization › http://j.mp/fb_optimize
#-------------------------------------------------------------------

og_image:                   "https://aspectran.com/assets/img/aspectran-logo.png"
og_locale:                  "en_US"
og_type:                    "website"
og_title:                   "Aspectran"
og_description:             "Aspectran is a lightweight framework for building high performance Java applications."
# og_url:                   ""
# og_site_name:             ""




#-------------------------------------------------------------------
# Sass
# More › http://sass-lang.com/
# More › http://jekyllrb.com/docs/assets/#sassscss
#-------------------------------------------------------------------

#sass:
#  sass_dir: _sass
#  style: :compressed



#-------------------------------------------------------------------
# Analytics
# https://www.google.com/analytics/
# used in _includes/header, _includes/google-translate
#-------------------------------------------------------------------

google_analytics_tracking_id: UA-66807210-2
